insert into `todos` (`id`, `name`, `description`) values (1, 'TITANIUM DIOXIDE, ZINC OXIDE', 'Unspecified superficial injury of other part of head, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (2, 'TITANIUM DIOXIDE', 'Other chronic hematogenous osteomyelitis, left shoulder');
insert into `todos` (`id`, `name`, `description`) values (3, 'codeine phosphate and guaifenesin', 'Bipolar disorder, current episode manic without psychotic features, severe');
insert into `todos` (`id`, `name`, `description`) values (4, 'Paroxetine', 'Toxic effect of tin and its compounds, undetermined, sequela');
insert into `todos` (`id`, `name`, `description`) values (5, 'glycerin, phenylephrine HCl, pramoxine HCl, white petrolatum', 'Passenger of special industrial vehicle injured in nontraffic acc`id`ent, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (6, 'Stavudine', 'Poisoning by anticholinesterase agents, assault, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (7, 'Guaifenesin and Dextromethorphan Hydrobrom`id`e', 'Burn of third degree of multiple sites of ankle and foot');
insert into `todos` (`id`, `name`, `description`) values (8, 'Hydroxychloroquine Sulfate', 'Nodular lymphocyte predominant Hodgkin lymphoma, lymph nodes of inguinal region and lower limb');
insert into `todos` (`id`, `name`, `description`) values (9, 'Terbinafine', 'Hematospermia');
insert into `todos` (`id`, `name`, `description`) values (10, 'Ondansetron', 'Melanoma in situ of left eyel`id`, including canthus');
insert into `todos` (`id`, `name`, `description`) values (11, 'OCTOCRYLENE, OCTINOXATE, TITANIUM DIOXIDE', 'Passenger in three-wheeled motor vehicle injured in noncollision transport acc`id`ent in traffic acc`id`ent, sequela');
insert into `todos` (`id`, `name`, `description`) values (12, 'Aluminum zirconium tetrachlorohydrex gly', 'Injury of tibial nerve at lower leg level, unspecified leg, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (13, 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'Injury of left internal carot`id` artery, intracranial portion, not elsewhere classified with loss of consciousness of 6 hours to 24 hours, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (14, 'Hyoscyamine Sulfate', 'Contusion of lung, bilateral, sequela');
insert into `todos` (`id`, `name`, `description`) values (15, 'Citrus limonum, Echinacea', 'Other mycoses, not elsewhere classified');
insert into `todos` (`id`, `name`, `description`) values (16, 'Body Flu`id` Balance', 'Unspecified fracture of lower end of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into `todos` (`id`, `name`, `description`) values (17, 'OCTINOXATE and TITANIUM DIOXIDE', 'Poisoning by antiviral drugs, assault, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (18, 'DIMETHICONE', 'Nondisplaced unspecified fracture of unspecified lesser toe(s), subsequent encounter for fracture with routine healing');
insert into `todos` (`id`, `name`, `description`) values (19, 'adapalene', 'Injury of unspecified nerve at shoulder and upper arm level, left arm, sequela');
insert into `todos` (`id`, `name`, `description`) values (20, 'TRICLOSAN', 'Idiopathic chronic gout, right hip');
insert into `todos` (`id`, `name`, `description`) values (21, 'temazepam', 'Other secondary kyphosis, thoracolumbar region');
insert into `todos` (`id`, `name`, `description`) values (22, 'Oxymetazoline hydrochlor`id`e', 'Encounter for surveillance of injectable contraceptive');
insert into `todos` (`id`, `name`, `description`) values (23, 'ascorbic', 'Other nondisplaced fracture of lower end of unspecified humerus, subsequent encounter for fracture with malunion');
insert into `todos` (`id`, `name`, `description`) values (24, 'Alcohol', 'Nondisplaced fracture of triquetrum [cuneiform] bone, right wrist, sequela');
insert into `todos` (`id`, `name`, `description`) values (25, 'HGH, Hepar Bovinum, Pituitary Bovinum', 'Other secondary chronic gout, shoulder');
insert into `todos` (`id`, `name`, `description`) values (26, 'Oxygen', 'Unspecified foreign body in pharynx causing asphyxiation, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (27, 'methylprednisolone', 'Dislocation of tarsometatarsal joint of right foot, sequela');
insert into `todos` (`id`, `name`, `description`) values (28, 'Italian Rye Grass', 'Military operations involving other firearms discharge');
insert into `todos` (`id`, `name`, `description`) values (29, 'Zinc Ox`id`e', 'Non-pressure chronic ulcer of left heel and m`id`foot with necrosis of muscle');
insert into `todos` (`id`, `name`, `description`) values (30, 'Cyclophospham`id`e', 'Congenital kyphosis, cervical region');
insert into `todos` (`id`, `name`, `description`) values (31, 'Nitrogen', 'Laceration without foreign body of left wrist');
insert into `todos` (`id`, `name`, `description`) values (32, 'Titanium Diox`id`e', 'Corrosion of second degree of unspecified ankle, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (33, 'Acetaminophen', 'Puncture wound without foreign body, unspecified ankle, sequela');
insert into `todos` (`id`, `name`, `description`) values (34, 'Ranit`id`ine', 'Anterior dislocation of right humerus');
insert into `todos` (`id`, `name`, `description`) values (35, 'Megestrol Acetate', 'Crushing injury of other specified parts of neck');
insert into `todos` (`id`, `name`, `description`) values (36, 'Plantain English', 'Other acc`id`ent with babystroller');
insert into `todos` (`id`, `name`, `description`) values (37, 'TITANIUM DIOXIDE', 'Vertiginous syndromes in diseases classified elsewhere');
insert into `todos` (`id`, `name`, `description`) values (38, 'Adonis vernalis, ATP (Adenosine triphosphate)', 'Torus fracture of lower end of unspecified femur, subsequent encounter for fracture with routine healing');
insert into `todos` (`id`, `name`, `description`) values (39, 'Dextromethorphan, Guaifenesin, Phenylephrine', 'Partially resolved traumatic cataract, unspecified eye');
insert into `todos` (`id`, `name`, `description`) values (40, 'Promethazine Hydrochlor`id`e', 'Poisoning by mixed bacterial vaccines without a pertussis component, undetermined, sequela');
insert into `todos` (`id`, `name`, `description`) values (41, 'Dapsone', 'Underdosing of androgens and anabolic congeners, sequela');
insert into `todos` (`id`, `name`, `description`) values (42, 'ibuprofen', 'Minor contusion of spleen, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (43, 'Arsenic Triox`id`e, Anamirta Cocculus Seed', 'Burn of third degree of unspecified lower leg, sequela');
insert into `todos` (`id`, `name`, `description`) values (44, 'Sodium Flour`id`e', 'Toxic effect of nitroderivatives and aminoderivatives of benzene and its homologues, undetermined, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (45, 'POLYETHYLENE GLYCOL 3350', 'Allergic rhinitis due to pollen');
insert into `todos` (`id`, `name`, `description`) values (46, 'enoxaparin sodium', 'Person boarding or alighting a car injured in collision with other nonmotor vehicle');
insert into `todos` (`id`, `name`, `description`) values (47, 'Acetaminophen', 'Unspecified fracture of shaft of unspecified femur, subsequent encounter for open fracture type I or II with delayed healing');
insert into `todos` (`id`, `name`, `description`) values (48, 'Labetalol Hydrochlor`id`e', 'Nondisplaced fracture of distal phalanx of left ring finger');
insert into `todos` (`id`, `name`, `description`) values (49, 'Salicylic Ac`id`', 'Other specified crystal arthropathies, unspecified knee');
insert into `todos` (`id`, `name`, `description`) values (50, 'alcohol', 'Displaced trimalleolar fracture of left lower leg, subsequent encounter for open fracture type I or II with nonunion');
insert into `todos` (`id`, `name`, `description`) values (51, 'Salsalate', 'Acute suppurative otitis media without spontaneous rupture of ear drum, recurrent, bilateral');
insert into `todos` (`id`, `name`, `description`) values (52, 'Clotrimazole', 'Strain of extensor muscle, fascia and tendon of left index finger at forearm level, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (53, 'Petrolatum', 'Pathological fracture in neoplastic disease, right fibula, subsequent encounter for fracture with delayed healing');
insert into `todos` (`id`, `name`, `description`) values (54, 'Bacitracin L`id`ocaine', 'Laceration of fallopian tube, bilateral, sequela');
insert into `todos` (`id`, `name`, `description`) values (55, 'Natures Antibac Orange Vanilla', 'Superficial frostbite of toe(s)');
insert into `todos` (`id`, `name`, `description`) values (56, 'Aluminum Zirconium Tetrachlorohydrex GLY', 'Poisoning by angiotensin-converting-enzyme inhibitors, assault, sequela');
insert into `todos` (`id`, `name`, `description`) values (57, 'ZINC OXIDE and TITANIUM DIOXIDE', 'Burn of third degree of right axilla, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (58, 'External Analgesic Plaster for Removal of Corns and Calluses', 'Pathological fracture, unspecified toe(s), initial encounter for fracture');
insert into `todos` (`id`, `name`, `description`) values (59, 'Chlorpheniramine Maleate and Codeine Phosphate', 'Poisoning by vitamins, acc`id`ental (unintentional)');
insert into `todos` (`id`, `name`, `description`) values (60, 'edetate calcium disodium', 'Newborn light for gestational age');
insert into `todos` (`id`, `name`, `description`) values (61, 'Ear Wax Removal Complete Kit', 'Complete traumatic amputation of one left lesser toe, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (62, 'CALCIUM CHLORIDE', 'Other subluxation and dislocation of shoulder joint');
insert into `todos` (`id`, `name`, `description`) values (63, 'Metformin Hydrochlor`id`e', 'Subluxation and dislocation of thoracic vertebra');
insert into `todos` (`id`, `name`, `description`) values (64, 'zolp`id`em tartrate', 'Traumatic hemorrhage of cerebrum, unspecified, with loss of consciousness of 30 minutes or less, sequela');
insert into `todos` (`id`, `name`, `description`) values (65, 'Bupropion Hydrochlor`id`e', 'Major laceration of left k`id`ney');
insert into `todos` (`id`, `name`, `description`) values (66, 'Aconitum napellus, Chamomilla, Coffea cruda,', 'Dislocation of jaw, left s`id`e, sequela');
insert into `todos` (`id`, `name`, `description`) values (67, 'morphine sulfate', 'Juvenile `id`iopathic scoliosis, thoracolumbar region');
insert into `todos` (`id`, `name`, `description`) values (68, 'OCTINOXATE, OCTISALATE', 'Displaced fracture of right radial stylo`id` process, subsequent encounter for open fracture type I or II with routine healing');
insert into `todos` (`id`, `name`, `description`) values (69, 'Losartan Potassium', 'Corrosion of second degree of nose (septum)');
insert into `todos` (`id`, `name`, `description`) values (70, 'isoleucine, leucine, tryptophan, valine, alani', 'Displaced spiral fracture of shaft of unspecified tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into `todos` (`id`, `name`, `description`) values (71, 'Cochlearia officinalis, Ipecacuanha,', 'Other fracture of third thoracic vertebra, initial encounter for closed fracture');
insert into `todos` (`id`, `name`, `description`) values (72, 'Petrolatum', 'Person on outs`id`e of pick-up truck or van injured in collision with pedal cycle in traffic acc`id`ent, sequela');
insert into `todos` (`id`, `name`, `description`) values (73, 'METHYL SALICYLATE, MENTHOL, CAPSAICIN', 'Algoneurodystrophy');
insert into `todos` (`id`, `name`, `description`) values (74, 'Arsenicum alb., Benzoicum, Chionanthus, Valeriana', 'Displaced comminuted supracondylar fracture without intercondylar fracture of left humerus, initial encounter for closed fracture');
insert into `todos` (`id`, `name`, `description`) values (75, 'Alcohol', 'Corrosion of unspecified degree, sequela');
insert into `todos` (`id`, `name`, `description`) values (76, 'OCTINOXATE OXYBENZONE TITANIUM DIOXIDE', 'Poisoning by other drug primarily affecting the autonomic nervous system, intentional self-harm, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (77, 'Loperam`id`e Hydrochlor`id`e', 'War operations involving unspecified explosion and fragments, military personnel, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (78, 'Titanium Diox`id`e', 'Injury of oculomotor nerve, right s`id`e, sequela');
insert into `todos` (`id`, `name`, `description`) values (79, 'Simvastatin', 'Laceration with foreign body of right ear, sequela');
insert into `todos` (`id`, `name`, `description`) values (80, 'HYDROCHLOROTHIAZIDE', 'Displaced fracture of medial phalanx of left m`id`dle finger, subsequent encounter for fracture with malunion');
insert into `todos` (`id`, `name`, `description`) values (81, 'olmesartan medoxomil', 'Crushed between passenger ship and other watercraft or other object due to collision, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (82, 'Oxaliplatin', 'Unspecified injury of extensor muscle, fascia and tendon of other finger at wrist and hand level, sequela');
insert into `todos` (`id`, `name`, `description`) values (83, 'Oxygen', 'Other embolism in pregnancy, first trimester');
insert into `todos` (`id`, `name`, `description`) values (84, 'Triclosan', 'Unspecified injury of ovary, unspecified, sequela');
insert into `todos` (`id`, `name`, `description`) values (85, 'Ketoprofen', 'Labor and delivery complicated by cord around neck, without compression, other fetus');
insert into `todos` (`id`, `name`, `description`) values (86, 'PANTOPRAZOLE SODIUM', 'Nondisplaced apophyseal fracture of left femur, initial encounter for closed fracture');
insert into `todos` (`id`, `name`, `description`) values (87, 'Whole Egg', 'Unspecified fracture of head of right femur, sequela');
insert into `todos` (`id`, `name`, `description`) values (88, 'Verapamil Hydrochlor`id`e', 'Laceration without foreign body of abdominal wall, right upper quadrant without penetration into peritoneal cavity, subsequent encounter');
insert into `todos` (`id`, `name`, `description`) values (89, 'Risper`id`one', 'Unspecified trochanteric fracture of left femur, subsequent encounter for closed fracture with delayed healing');
insert into `todos` (`id`, `name`, `description`) values (90, 'Pantoprazole Sodium', 'Unspecified injury of other flexor muscle, fascia and tendon at forearm level, unspecified arm, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (91, 'CALCAREA FLUORICA', 'Person on outs`id`e of three-wheeled motor vehicle injured in collision with car, pick-up truck or van in traffic acc`id`ent, sequela');
insert into `todos` (`id`, `name`, `description`) values (92, 'Ibuprofen and Diphenhydramine HCl', 'Lead-induced chronic gout, right wrist');
insert into `todos` (`id`, `name`, `description`) values (93, 'Homosalate, Octisalate, Oxybenzone, Avobenzone', 'Spotting complicating pregnancy, third trimester');
insert into `todos` (`id`, `name`, `description`) values (94, 'prim`id`one', 'Nondisplaced fracture of medial condyle of left femur, subsequent encounter for open fracture type I or II with malunion');
insert into `todos` (`id`, `name`, `description`) values (95, 'Phenylephrine HCl', 'Breakdown (mechanical) of other urinary catheter, sequela');
insert into `todos` (`id`, `name`, `description`) values (96, 'Octinoxate', 'Non-pressure chronic ulcer of skin of other sites with necrosis of bone');
insert into `todos` (`id`, `name`, `description`) values (97, 'Oxcarbazepine', 'Drowning and submersion due to falling or jumping from burning sailboat, initial encounter');
insert into `todos` (`id`, `name`, `description`) values (98, 'Mexican Tea', 'Conjunctival edema, unspecified eye');
insert into `todos` (`id`, `name`, `description`) values (99, 'THIOTEPA', 'Corrosion of unspecified degree of multiple sites of unspecified wrist and hand, sequela');
insert into `todos` (`id`, `name`, `description`) values (100, 'Benzoyl Perox`id`e', 'Burn due to localized fire on board unspecified watercraft');
